create database monitrack;
use monitrack;
DROP TABLE IF EXISTS PERSON;
CREATE TABLE IF NOT EXISTS PERSON (
  ID int(11) NOT NULL AUTO_INCREMENT,
  LAST_NAME varchar(50) NOT NULL,
  FIRST_NAME varchar(50) NOT NULL,
  ROLE varchar(50) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  ARRIVAL_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

select * from person;