USE monitrack;

DELIMITER //
DROP TABLE IF EXISTS IP_ADDRESS;
CREATE TABLE IF NOT EXISTS IP_ADDRESS (
  ID_ADDRESS int(11) NOT NULL AUTO_INCREMENT,
  IP_ADDRESS varchar(17) NOT NULL UNIQUE,
  IS_ADDRESS_AVAILABLE int(11),
  PRIMARY KEY (ID_ADDRESS)  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
//
DROP TABLE IF EXISTS MAC_ADDRESS;
//
CREATE TABLE IF NOT EXISTS MAC_ADDRESS (
  ID_ADDRESS int(11) NOT NULL AUTO_INCREMENT,
  MAC_ADDRESS varchar(17) NOT NULL UNIQUE,
  IS_ADDRESS_AVAILABLE int(11),
  PRIMARY KEY (ID_ADDRESS)  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
//