USE monitrack;
DELIMITER //
--
-- Base de données :  monitrack
--
-- --------------------------------------------------------

--
-- Structure de la table SENSOR
--

DROP TABLE IF EXISTS SENSOR;
CREATE TABLE IF NOT EXISTS SENSOR (
  ID_SENSOR int(11) NOT NULL AUTO_INCREMENT,
  TYPE varchar(25) NOT NULL,
  MAC_ADDRESS varchar(17),
  SERIAL_NUMBER varchar(25) NOT NULL,
  HARDWARE_VERSION decimal(11,4) NOT NULL,
  SOFTWARE_VERSION decimal(11,4) NOT NULL,
  PRIMARY KEY (ID_SENSOR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
//
create trigger attribute_mac_address_to_sensor_trigger
before insert
on SENSOR
for each row
BEGIN
	DECLARE macAddress varchar(17);
    select MAC_ADDRESS into macAddress from MAC_ADDRESS where IS_AVAILABLE = 1 LIMIT 1; 
    update MAC_ADDRESS set IS_AVAILABLE = 0, ID_SENSOR = new.ID_SENSOR, ATTRIBUTION_DATE = CURRENT_TIMESTAMP where MAC_ADDRESS = macAddress;
	set new.MAC_ADDRESS = macAddress;
END
//
-- --------------------------------------------------------

--
-- Structure de la table SENSOR_CONFIGURATION
--

DROP TABLE IF EXISTS SENSOR_CONFIGURATION;
CREATE TABLE IF NOT EXISTS SENSOR_CONFIGURATION (
  ID_SENSOR_CONFIGURATION int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR int(11),
  ACTIVITY varchar(25) NOT NULL,
  ID_LOCATION int(11) DEFAULT NULL,
  IP_ADDRESS varchar(15) DEFAULT NULL,
  CREATION_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MESSAGE_DATE timestamp DEFAULT CURRENT_TIMESTAMP,
  LAST_CONFIGURATION_DATE timestamp DEFAULT CURRENT_TIMESTAMP,
  START_ACTIVITY_TIME time DEFAULT NULL,
  END_ACTIVITY_TIME time DEFAULT NULL,
  CHECK_FREQUENCY int(11) DEFAULT NULL,
  MEASUREMENT_UNIT varchar(255) ,
  CURRENT_THRESHOLD decimal(11,4) DEFAULT NULL,
  MIN_DANGER_THRESHOLD decimal(11,4) DEFAULT NULL,
  MAX_DANGER_THRESHOLD decimal(11,4) DEFAULT NULL,
  POSITION_X decimal(11,4) DEFAULT NULL,
  POSITION_Y decimal(11,4) DEFAULT NULL,
  PRIMARY KEY (ID_SENSOR_CONFIGURATION),
  CONSTRAINT FK_ID_SENSOR_CONFIGURATION FOREIGN KEY(ID_SENSOR) REFERENCES SENSOR(ID_SENSOR) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

//

-- --------------------------------------------------------

--
-- Structure de la table SENSOR_CONFIGURATION_HISTORY
--
//
DROP TABLE IF EXISTS SENSOR_CONFIGURATION_HISTORY;
CREATE TABLE IF NOT EXISTS SENSOR_CONFIGURATION_HISTORY (
  ID_HISTORY int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR_CONFIGURATION int(11) NOT NULL,
  MEASURED_THRESHOLD decimal(11,4) NOT NULL,
  MAX_DANGER_THRESHOLD decimal(11,4) NOT NULL,
  MIN_DANGER_THRESHOLD decimal(11,4) NOT NULL,
  MEASUREMENT_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  END_ALERT_DATE timestamp,
  DESCRIPTION varchar(300),
  ACTION_DONE varchar(300),
  PRIMARY KEY (ID_HISTORY)
  CONSTRAINT FK_ID_SENSOR_CONFIGURATION_HISTORY FOREIGN KEY(ID_SENSOR_CONFIGURATION) REFERENCES SENSOR_CONFIGURATION(ID_SENSOR_CONFIGURATION) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

//
-- --------------------------------------------------------

--
-- Structure de la table IP_ADDRESS
--

DROP TABLE IF EXISTS IP_ADDRESS;
CREATE TABLE IF NOT EXISTS IP_ADDRESS (
  ID_ADDRESS int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR_CONFIGURATION int(11),
  IP_ADDRESS varchar(17) NOT NULL UNIQUE,
  ATTRIBUTION_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IS_AVAILABLE int(1) NOT NULL,
  PRIMARY KEY (ID_ADDRESS)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table MAC_ADDRESS
--
//
DROP TABLE IF EXISTS MAC_ADDRESS;
CREATE TABLE IF NOT EXISTS MAC_ADDRESS (
  ID_ADDRESS int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR_CONFIGURATION int(11),
  MAC_ADDRESS varchar(17) NOT NULL UNIQUE,
  ATTRIBUTION_DATE timestamp,
  IS_AVAILABLE int(1) NOT NULL,
  PRIMARY KEY (ID_ADDRESS)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
//


-- --------------------------------------------------------
//
--
-- Structure de la table MANUAL_TRIGGER_HISTORY
--

DROP TABLE IF EXISTS MANUAL_TRIGGER_HISTORY;
CREATE TABLE IF NOT EXISTS MANUAL_TRIGGER_HISTORY (
  ID_HISTORY int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR_CONFIGURATION int(11),
  ID_LOCATION int(11) NOT NULL,
  CODE_ENTERED varchar(50),
  TRIGGERING_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ACCESS_GRANTED int(1),
  PRIMARY KEY (ID),
  CONSTRAINT FK_ID_LOCATION_TRIGGER FOREIGN KEY(ID_LOCATION) REFERENCES LOCATION(ID_LOCATION) ON DELETE CASCADE,
  CONSTRAINT FK_ID_SENSOR_MANUAL_CONTROL_HISTORY FOREIGN KEY(ID_SENSOR_CONFIGURATION) REFERENCES SENSOR_CONFIGURATION(ID_SENSOR_CONFIGURATION) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------


COMMIT;


