CREATE DATABASE IF NOT EXISTS monitrack;
use monitrack;

DROP TABLE IF EXISTS SENSOR;
CREATE TABLE IF NOT EXISTS SENSOR (
  ID_SENSOR int(11) NOT NULL AUTO_INCREMENT,
  TYPE varchar(25) NOT NULL,
  MAC_ADDRESS varchar(17),
  SERIAL_NUMBER varchar(25) NOT NULL,
  HARDWARE_VERSION decimal(11,4) NOT NULL,
  SOFTWARE_VERSION decimal(11,4) NOT NULL,
  PRIMARY KEY (ID_SENSOR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS SENSOR_SHOP;
CREATE TABLE IF NOT EXISTS SENSOR_SHOP (
  ID_SENSOR_SHOP int(11) NOT NULL AUTO_INCREMENT,
  ID_SENSOR int(11),
  MARK varchar(25) NOT NULL,
  MODEL varchar(17),
  PURCHASE_COST decimal(11,4) NOT NULL,
  MAINTENANCE_COST decimal(11,4) NOT NULL,
  PRIMARY KEY (ID_SENSOR_SHOP),
  CONSTRAINT FK_ID_SENSOR_SHOP FOREIGN KEY(ID_SENSOR_SHOP) REFERENCES SENSOR(ID_SENSOR) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
